### ISSUE TITLE
Clarify recipe run order

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-docs#226]
There is some general confusion on the order the recipes are run in. This is exacerbated by the fact that some of the terminology is unintuitive. 

We should update the docs to clarify the order that recipes get run in.

To write down some examples:

Example `rewrite.yml` file:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.RecipeA
displayName: Recipe A
description: Applies Recipe B.
recipeList:
  - com.yourorg.RecipeB:
  - com.yourorg.RecipeC
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.Foo
...
recipeList:
  - com.yourorg.bar:
  - com.yourorg.bash
``` 

If a `rewrite.yml` file is declared that looks sort of like the above then it's _possible_ for `Recipe A` to run before `Foo` -- but it's also possible for `Foo` to run before `Recipe A`. This recipe run order depends on the order the recipes were activated.

So if, in Gradle, the recipes were activated like this:

```groovy
rewrite {
    activeRecipe(
        'com.yourorg.Foo',
        'com.yourorg.RecipeA'
    )
}
```

Then `Foo` would be run before `RecipeA`. Furthermore, `com.yourorg.bar` would run before `com.yourorg.bash` -- which would also run before `RecipeA`, `RecipeB`, and `RecipeC`.
