### ISSUE TITLE
Please refine documentation of org.openrewrite.java.logging.ParameterizedLogging

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-docs#249]
I try to get https://docs.openrewrite.org/recipes/java/logging/parameterizedlogging running in my project.

I would like to change the parameterization of all log levels... Think, I need to enumarate all of them?

I tried with two, but no change in my code

```yaml
 - org.openrewrite.java.logging.ParameterizedLogging:
     methodPattern: org.slf4j.Logger info(..)
     remoteToString: true
 - org.openrewrite.java.logging.ParameterizedLogging:
     methodPattern: org.slf4j.Logger debug(..)
     remoteToString: true
```

Following statement is still unchanged:

```java
LOGGER.info(String.format("Truncated the too long filename '%s' (%d characters) to '%s'.", fileName, fileName.length(), shortName));
```

---

Maybe, this could also be a wish for a new recipe?

> Replace `String.format` by parameterized logging statements
