### ISSUE TITLE
Issue with Precondition documentation generation

### ISSUE THREAD

**Issue by SimonVerhoeven** [openrewrite/rewrite-docs#250]
For recipes such as https://docs.openrewrite.org/recipes/java/spring/boot3/enablevirtualthreads which contain a precondition (in this case `org.openrewrite.java.search.HasJavaVersion` the recipe list shows `Precondition bellwether` which links to https://github.com/openrewrite/rewrite-docs/blob/master/reference/recipes/config/declarativerecipe$preconditionbellwether.md rather than the expected HasJavaVersion recipe + link.

**Comment by timtebeek** [comment]
Thanks for pointing this out! You've found a neat implementation detail around how we handle preconditions in declarative recipes; the message you saw [originates here](https://github.com/openrewrite/rewrite/blob/v8.9.9/rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java#L131-L132). Since the class is package private the best I could do for now is recognize such recipes by their message, and [then skip them](https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/0fd23e6576b92c3f74e72ab136105e396ac63077).

**Comment by timtebeek** [comment]
Not fixed yes as per: https://openrewrite.github.io/rewrite-recipe-markdown-generator/reference/recipes/java/spring/boot3/enablevirtualthreads.html

**Comment by timtebeek** [comment]
So the issue here is that the bellwether is shown on the Yaml tab:
![image](https://github.com/openrewrite/rewrite-docs/assets/1027334/b4e35269-cc53-4ea5-a6f4-109fe3f96a2e)

That's an implementation detail; not something for folks to implement. Might mean we need to move this to
https://github.com/openrewrite/rewrite-recipe-markdown-generator

There it [shows up in the yaml](https://openrewrite.github.io/rewrite-recipe-markdown-generator/reference/recipes/java/spring/boot3/enablevirtualthreads.html) tab as
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.EnableVirtualThreads
displayName: Enable Virtual Threads on Java 21
description: Set `spring.threads.virtual.enabled` to `true` in `application.properties` or `application.yml`.
recipeList:
  - org.openrewrite.config.DeclarativeRecipe$PreconditionBellwether
  - org.openrewrite.java.spring.AddSpringProperty
```

**Comment by timtebeek** [comment]
Compare that to how the recipe is actually implemented:
https://github.com/openrewrite/rewrite-spring/blob/b76e03437143632ec9d42ffc0a5e7af2b88f11c9/src/main/resources/META-INF/rewrite/spring-boot-32.yml#L63-L73

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.EnableVirtualThreads
displayName: Enable Virtual Threads on Java 21
description: Set `spring.threads.virtual.enabled` to `true` in `application.properties` or `application.yml`.
preconditions:
  - org.openrewrite.java.search.HasJavaVersion:
      version: 21.X
recipeList:
  - org.openrewrite.java.spring.AddSpringProperty:
      property: spring.threads.virtual.enabled
      value: true
```

**Comment by timtebeek** [comment]
As discussed on the above PR: it would be better to show the configured precondition & recipe arguments in the bellwether. So right now what we show is:

## Current
No bellwether (good),
no precondition (missed opportunity, it's in the bellwether),
no arguments to AddSpringProperty, (leading to a broken yaml recipe)
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.EnableVirtualThreads
displayName: Enable Virtual Threads on Java 21
description: Set `spring.threads.virtual.enabled` to `true` in `application.properties` or `application.yml`.
recipeList:
  - org.openrewrite.java.spring.AddSpringProperty
```

## Ideal
As per [the source](https://github.com/openrewrite/rewrite-spring/blob/b76e03437143632ec9d42ffc0a5e7af2b88f11c9/src/main/resources/META-INF/rewrite/spring-boot-32.yml#L63-L73)
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.EnableVirtualThreads
displayName: Enable Virtual Threads on Java 21
description: Set `spring.threads.virtual.enabled` to `true` in `application.properties` or `application.yml`.
preconditions:
  - org.openrewrite.java.search.HasJavaVersion:
      version: 21.X
recipeList:
  - org.openrewrite.java.spring.AddSpringProperty:
      property: spring.threads.virtual.enabled
      value: true
```
