### ISSUE TITLE
Minor note, UseStaticImports uses incorrect yaml indent; in 7.x has different parameter key

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-docs#36]
This isn't a priority, I don't have time to fix it just right yet, I'm just logging it because I spotted it and it may be in other places. Feel free to close whenever.

The `UseStaticImport` 6.x reference docs has broken indentation on the parameter value https://github.com/openrewrite/rewrite-docs/blob/926f06a694cab31b2566d0f7c92c572cfaf5d4a5/reference/java/refactoring-java-source-code/usestaticimport.md#yaml-definition

specifically, this:
```yaml
type: specs.openrewrite.org/v1beta/visitor
name: com.yourorg.UseStaticJUnitAsserts
visitors:
  - org.openrewrite.java.UseStaticImport:
    method: 'org.junit.jupiter.api.Assertions assert*(..)'
```

should be this:

```yaml
type: specs.openrewrite.org/v1beta/visitor
name: com.yourorg.UseStaticJUnitAsserts
visitors:
  - org.openrewrite.java.UseStaticImport:
      method: 'org.junit.jupiter.api.Assertions assert*(..)' # <-- note the indentation
```

---

And, also minor, but for future reference, in 7.x, `method` changes to `methodPattern` https://github.com/openrewrite/rewrite/blob/d7a15d40a20088f7a98fcc603d61216c677b621a/rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java#L38

Again, not a big deal, I'm just pointing it out for visibility. Feel free to close whenever
